
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package rs.ac.uns.ftn.xws.cbs.banka;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-03-28T00:09:13.712+01:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "BankaService",
                      portName = "Banka",
                      targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/banka",
                      wsdlLocation = "file:/C:/Users/Nikola/Desktop/Fax/4 godina/2 semestar/xws/workspace/xws-cbs-banka/WEB-INF/xml/Banka.wsdl",
                      endpointInterface = "rs.ac.uns.ftn.xws.cbs.banka.Banka")
                      
public class BankaImpl implements Banka {

    private static final Logger LOG = Logger.getLogger(BankaImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.Banka#posaljiIzvod(rs.ac.uns.ftn.xws.cbs.zahtev_za_izvod.ZahtevZaIzvod  zahtev )*
     */
    public rs.ac.uns.ftn.xws.cbs.izvod.Izvod posaljiIzvod(rs.ac.uns.ftn.xws.cbs.zahtev_za_izvod.ZahtevZaIzvod zahtev) { 
        LOG.info("Executing operation posaljiIzvod");
        System.out.println(zahtev);
        try {
            rs.ac.uns.ftn.xws.cbs.izvod.Izvod _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.Banka#primiMT103(rs.ac.uns.ftn.xws.cbs.mt103.Mt103  mt103 )*
     */
    public void primiMT103(rs.ac.uns.ftn.xws.cbs.mt103.Mt103 mt103) { 
        LOG.info("Executing operation primiMT103");
        System.out.println(mt103);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.Banka#primiMT910(rs.ac.uns.ftn.xws.cbs.mt910.Mt910  mt910 )*
     */
    public void primiMT910(rs.ac.uns.ftn.xws.cbs.mt910.Mt910 mt910) { 
        LOG.info("Executing operation primiMT910");
        System.out.println(mt910);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.Banka#primiNalog(rs.ac.uns.ftn.xws.cbs.nalog_za_placanje.NalogZaPlacanje  nalog )*
     */
    public void primiNalog(rs.ac.uns.ftn.xws.cbs.nalog_za_placanje.NalogZaPlacanje nalog) { 
        LOG.info("Executing operation primiNalog");
        System.out.println(nalog);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.Banka#primiMT102(rs.ac.uns.ftn.xws.cbs.mt102.Mt102  mt102 )*
     */
    public void primiMT102(rs.ac.uns.ftn.xws.cbs.mt102.Mt102 mt102) { 
        LOG.info("Executing operation primiMT102");
        System.out.println(mt102);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.Banka#primiMT900(rs.ac.uns.ftn.xws.cbs.mt900.Mt900  mt900 )*
     */
    public void primiMT900(rs.ac.uns.ftn.xws.cbs.mt900.Mt900 mt900) { 
        LOG.info("Executing operation primiMT900");
        System.out.println(mt900);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
