
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package rs.ac.uns.ftn.xws.cbs.banka;

import java.util.logging.Logger;

import rs.ac.uns.ftn.xws.cbs.izvod.Izvod;
import singleton.MainBankProcessor;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-04-12T00:24:21.829+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "BankaService",
                      portName = "Banka",
                      targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/banka",
                      endpointInterface = "rs.ac.uns.ftn.xws.cbs.banka.Banka")
                      
public class BankaImpl implements Banka {

    private static final Logger LOG = Logger.getLogger(BankaImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.Banka#primiMT102(rs.ac.uns.ftn.xws.cbs.mt102.Mt102  mt102 )*
     */
    public void primiMT102(rs.ac.uns.ftn.xws.cbs.mt102.Mt102 mt102) { 
        LOG.info("Executing operation primiMT102");
        System.out.println(mt102);
        try {
        	
        	MainBankProcessor.getInstance().process(mt102);
        	
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.Banka#primiMT103(rs.ac.uns.ftn.xws.cbs.mt103.Mt103  mt103 )*
     */
    public void primiMT103(rs.ac.uns.ftn.xws.cbs.mt103.Mt103 mt103) { 
        LOG.info("Executing operation primiMT103");
        System.out.println(mt103);
        try {
        	
        	MainBankProcessor.getInstance().process(mt103);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.Banka#primiMT900(rs.ac.uns.ftn.xws.cbs.mt900.Mt900  mt900 )*
     */
    public void primiMT900(rs.ac.uns.ftn.xws.cbs.mt900.Mt900 mt900) { 
        LOG.info("Executing operation primiMT900");
        System.out.println(mt900);
        try {
        	
        	MainBankProcessor.getInstance().process(mt900);
        	
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.Banka#primiMT910(rs.ac.uns.ftn.xws.cbs.mt910.Mt910  mt910 )*
     */
    public void primiMT910(rs.ac.uns.ftn.xws.cbs.mt910.Mt910 mt910) { 
        LOG.info("Executing operation primiMT910");
        System.out.println(mt910);
        try {
        	
        	MainBankProcessor.getInstance().process(mt910);
        	
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.Banka#posaljiIzvod(rs.ac.uns.ftn.xws.cbs.zahtev_za_izvod.ZahtevZaIzvod  zahtev )*
     */
    public rs.ac.uns.ftn.xws.cbs.izvod.Izvod posaljiIzvod(rs.ac.uns.ftn.xws.cbs.zahtev_za_izvod.ZahtevZaIzvod zahtev) { 
        LOG.info("Executing operation posaljiIzvod");
        System.out.println(zahtev);
        try {
        	
            return (Izvod) MainBankProcessor.getInstance().process(zahtev);
            
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.Banka#primiNalog(rs.ac.uns.ftn.xws.cbs.nalog_za_placanje.NalogZaPlacanje  nalog )*
     */
    public void primiNalog(rs.ac.uns.ftn.xws.cbs.nalog_za_placanje.NalogZaPlacanje nalog) { 
        LOG.info("Executing operation primiNalog");
        System.out.println(nalog);
        try {
        	
        	MainBankProcessor.getInstance().process(nalog);
        	
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
