
package rs.ac.uns.ftn.xws.cbs.banka;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-23T17:53:36.387+02:00
 * Generated source version: 2.6.5
 * 
 */
 
public class XWSBanka_XWSBankaPort_Server{

    protected XWSBanka_XWSBankaPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new XWSBankaImpl();
        String address = "http://localhost:8080/Banka";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new XWSBanka_XWSBankaPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
