
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package rs.ac.uns.ftn.xws.cbs.banka;

import java.util.logging.Logger;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import rs.ac.uns.ftn.xws.cbs.izvod.Izvod;
import singleton.MainBankProcessor;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-06-23T17:53:36.365+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.ejb.Stateless
@javax.jws.WebService(
                      serviceName = "XWSBankaService",
                      portName = "XWSBankaPort",
                      targetNamespace = "http://www.ftn.uns.ac.rs/xws/cbs/banka",
                      wsdlLocation = "WEB-INF/xml/XWSBanka.wsdl",
                      endpointInterface = "rs.ac.uns.ftn.xws.cbs.banka.XWSBanka")
                      
public class XWSBankaImpl implements XWSBanka {

    private static final Logger LOG = Logger.getLogger(XWSBankaImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.XWSBanka#posaljiIzvod(rs.ac.uns.ftn.xws.cbs.zahtev_za_izvod.ZahtevZaIzvod  zahtev )*
     */
    public rs.ac.uns.ftn.xws.cbs.izvod.Izvod posaljiIzvod(rs.ac.uns.ftn.xws.cbs.zahtev_za_izvod.ZahtevZaIzvod zahtev) { 
        LOG.info("Executing operation posaljiIzvod");
        System.out.println(zahtev);
        try {
            return (Izvod) MainBankProcessor.getInstance().process(zahtev);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.XWSBanka#primiMT103(rs.ac.uns.ftn.xws.cbs.mt103.Mt103  mt103 )*
     */
    public void primiMT103(rs.ac.uns.ftn.xws.cbs.mt103.Mt103 mt103) { 
        LOG.info("Executing operation primiMT103");
        System.out.println(mt103);
        try {
        	MainBankProcessor.getInstance().process(mt103);
        	System.out.println("Processed MT103: "+mt103);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.XWSBanka#primiMT910(rs.ac.uns.ftn.xws.cbs.mt910.Mt910  mt910 )*
     */
    public void primiMT910(rs.ac.uns.ftn.xws.cbs.mt910.Mt910 mt910) { 
        LOG.info("Executing operation primiMT910");
        System.out.println(mt910);
        try {
        	MainBankProcessor.getInstance().process(mt910);
        	System.out.println("Processed MT910: "+mt910);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.XWSBanka#primiNalog(rs.ac.uns.ftn.xws.cbs.nalog_za_placanje.NalogZaPlacanje  nalog )*
     */
    public void primiNalog(rs.ac.uns.ftn.xws.cbs.nalog_za_placanje.NalogZaPlacanje nalog) { 
        LOG.info("Executing operation primiNalog");
        System.out.println(nalog);
        try {
        	MainBankProcessor.getInstance().process(nalog);
        	System.out.println("Processed nalog: "+nalog);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.XWSBanka#primiMT102(rs.ac.uns.ftn.xws.cbs.mt102.Mt102  mt102 )*
     */
    public void primiMT102(rs.ac.uns.ftn.xws.cbs.mt102.Mt102 mt102) { 
        LOG.info("Executing operation primiMT102");
        System.out.println(mt102);
        try {
        	MainBankProcessor.getInstance().process(mt102);
        	System.out.println("Processed MT102: "+mt102);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.xws.cbs.banka.XWSBanka#primiMT900(rs.ac.uns.ftn.xws.cbs.mt900.Mt900  mt900 )*
     */
    public void primiMT900(rs.ac.uns.ftn.xws.cbs.mt900.Mt900 mt900) { 
        LOG.info("Executing operation primiMT900");
        System.out.println(mt900);
        try {
        	MainBankProcessor.getInstance().process(mt900);
        	System.out.println("Processed MT900: "+mt900);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
